// Mock reviews data
export const mockReviews = [
  {
    id: 1,
    appName: "FitTrack Pro",
    rating: 5,
    reviewText: "Amazing app! The AI suggestions have helped me so much with my fitness journey.",
    reviewerName: "Sarah M.",
    date: new Date("2024-05-01"),
    platform: "App Store",
    status: "replied",
    aiGeneratedReply: "Thank you so much for the kind words, Sarah! We're thrilled that our AI suggestions are helping you on your fitness journey. Keep up the great work! 🎉",
    replyDate: new Date("2024-05-02"),
  },
  {
    id: 2,
    appName: "CloudSync",
    rating: 4,
    reviewText: "Good app overall, but the sync feature seems slow sometimes.",
    reviewerName: "John D.",
    date: new Date("2024-05-02"),
    platform: "Google Play",
    status: "pending",
    aiGeneratedReply: "Thank you for the feedback, John! We appreciate you reporting the sync speed issue. Our team is actively working on optimizations to improve performance. Please reach out to our support team for immediate assistance.",
    replyDate: null,
  },
  {
    id: 3,
    appName: "FitTrack Pro",
    rating: 1,
    reviewText: "Terrible experience. App keeps crashing.",
    reviewerName: "Mike R.",
    date: new Date("2024-05-03"),
    platform: "App Store",
    status: "ticket_created",
    aiGeneratedReply: "We sincerely apologize for the crashes you've experienced. This is not the experience we want for our users. We've created a support ticket (#TICKET-2024-001) to investigate this immediately.",
    replyDate: new Date("2024-05-03"),
  },
  {
    id: 4,
    appName: "CloudSync",
    rating: 4,
    reviewText: "Pretty solid app. Does what it says. Minor UI improvements would be nice.",
    reviewerName: "Emma L.",
    date: new Date("2024-05-04"),
    platform: "App Store",
    status: "replied",
    aiGeneratedReply: "Thank you for the constructive feedback, Emma! We really appreciate suggestions like yours. Our design team is always looking for ways to improve the UI experience. Your input helps us build a better product!",
    replyDate: new Date("2024-05-05"),
  },
  {
    id: 5,
    appName: "DataViz",
    rating: 3,
    reviewText: "It's okay but has bugs. Interface could be more intuitive.",
    reviewerName: "Alex T.",
    date: new Date("2024-05-05"),
    platform: "Google Play",
    status: "pending",
    aiGeneratedReply: "Thank you for your feedback, Alex. We understand that intuitive UI and bug-free performance are crucial. Our engineering team is working on the next release with improvements in both areas.",
    replyDate: null,
  },
];

export const mockBrandData = {
  brandName: "Fit Wellness Inc.",
  appCount: 3,
  totalReviews: 1247,
  averageRating: 4.2,
  personality: "Friendly, professional, motivational",
  tone: "Supportive and encouraging",
  communicationStyle: "We use empathy-first approach with action-oriented solutions",
};

export const mockFeatures = [
  {
    id: 1,
    title: "AI Trained For Your Brand",
    description: "Our proprietary AI learns and adapts to your brand's unique personality, style, and values. The more it works, the smarter it gets.",
    capabilities: [
      "Brand-Specific AI Training",
      "Continuous Learning from Your Feedback",
      "Personalized Brand Personality",
    ],
    icon: "Brain",
  },
  {
    id: 2,
    title: "Brand Vernacular Matching",
    description: "Replies automatically adapt to your unique brand voice, tone, and communication style. No more generic responses.",
    capabilities: [
      "Custom Brand Voice Training",
      "Tone Consistency Across All Replies",
      "Multi-Language Brand Voice Support",
    ],
    icon: "MessageSquare",
  },
  {
    id: 3,
    title: "10-Minute Lightning-Fast Replies",
    description: "Get intelligent, ready-to-send replies within 10 minutes of any review. Stay ahead of customer concerns.",
    capabilities: [
      "Real-Time Review Detection",
      "Instant AI Processing",
      "Immediate Notification Queue",
    ],
    icon: "Zap",
  },
  {
    id: 4,
    title: "Smart Ticketing Integration",
    description: "Critical 1-star reviews automatically become tickets in your support system for immediate attention",
    capabilities: [
      "Auto-Ticket for 1-Star Reviews",
      "Custom Ticket Rules & Automation",
      "Integration with Jira, Linear, Zendesk",
    ],
    icon: "Ticket",
  },
  {
    id: 5,
    title: "24/7 Fully Automated Responses",
    description: "No manual agents needed. Your reviews get intelligent, personalized replies 24/7 without human intervention",
    capabilities: [
      "Always-On Automation",
      "Zero Manual Work Required",
      "Consistent Quality Guaranteed",
    ],
    icon: "Clock",
  },
  {
    id: 6,
    title: "Weekly & Monthly Insights",
    description: "Get comprehensive reports tracking review volume, sentiment trends, and the impact of your automated replies",
    capabilities: [
      "Automated Weekly Summaries",
      "Monthly Performance Reports",
      "Sentiment Trend Analysis",
    ],
    icon: "BarChart3",
  },
];
