export const bybit = {
  slug: "bybit",
  name: "Bybit",
  searchTopic: "localized ASO case study",
  seoTitle: "Bybit ASO Case Study: Top 3 in Spain & Latin America | ASOWin",
  description: "How ASOWin helped Bybit achieve Top 3 rankings across Spain and Latin America through localized app store optimization and Spanish-language keyword strategy.",
  headline: "Top 3 rankings.",
  emphasis: "Spain & Latin America.",
  category: "Localized app store optimization",
  intro: "Bringing a global crypto platform closer to Spanish-speaking audiences through a focused app store strategy for Spain and Latin America.",
  background: "#17191c",
  visual: "markets",
  artCaption: "App store optimization for Spain and Latin America.",
  metric: "Top 3",
  metricLabel: "Reported rankings across Spain & Latin America",
  artTag: "SPANISH KEYWORDS · LOCALIZED LISTINGS",
  artLabel: "BYBIT × ASOWIN / LOCALIZED ASO",
  og: "/bybit-case-study-og.jpg",
  industry: "Crypto / FinTech",
  market: "Spain & Latin America",
  scopeLabel: "FOCUS",
  platforms: "Localized ASO",
  overviewTitle: "Improve app visibility in Spanish-speaking markets.",
  overview: [
    "Bybit is a cryptocurrency exchange offering spot trading, derivatives, and copy trading. With an established global presence, its next opportunity was to strengthen mobile discovery among Spanish-speaking audiences.",
    "The challenge was local relevance in a competitive crypto category. ASOWin focused on Spanish-language keyword visibility and store listing optimization, beginning in Spain with a broader focus on Latin America.",
  ],
  approachTitle: "Spanish keyword and store listing optimization.",
  approachIntro: "A localized ASO strategy connecting the platform’s offering with the searches that matter in Spanish-speaking markets.",
  services: [
    { tag: "MARKET FOCUS", title: "Optimize keyword rankings in Spain.", text: "The engagement began with Spain, focusing on keyword rankings and store listing optimization in a priority Spanish-speaking market.", href: "/services/app-store-optimization", linkLabel: "Explore our ASO approach" },
    { tag: "SPANISH KEYWORDS", title: "Target competitive crypto keywords in Spanish.", text: "Targeted competitive crypto-related keywords in Spanish to strengthen Bybit’s visibility where potential users search for trading apps.", href: "/services/app-store-optimization", linkLabel: "Explore keyword strategy" },
    { tag: "STORE LISTINGS", title: "Optimize localized store listings.", text: "Combined keyword optimization with a localized store listing strategy, helping connect Bybit’s product offering with Spanish-speaking audiences.", href: "/services/app-store-optimization", linkLabel: "Explore listing optimization" },
    { tag: "REGIONAL REACH", title: "Support organic acquisition in Latin America.", text: "Extended the strategic focus to Spanish-speaking Latin America, with organic acquisition and a stronger app store presence as the campaign goals.", href: "/services/app-store-optimization", linkLabel: "Explore localized ASO" },
  ],
  resultsTitle: "Top 3 rankings across Spain and Latin America.",
  resultsIntro: "ASOWin’s Bybit case study reports Top 3 rankings across Spain and Latin America following the localized ASO campaign.",
  results: [
    { label: "REPORTED RANKING RESULT", value: "Top 3", text: "Rankings achieved across Spain and Latin America, as reported in the campaign overview." },
    { label: "INITIAL MARKET", value: "Spain", text: "The starting point for keyword and store listing optimization." },
    { label: "REGIONAL FOCUS", value: "Latin America", text: "Spanish-speaking markets formed the wider focus of the localized strategy." },
  ],
  takeawayLabel: "LOCALIZED APP STORE OPTIMIZATION",
  takeaway: "ASOWin focused on Spanish-language crypto keywords and localized store listings. The campaign overview reports Top 3 rankings across Spain and Latin America.",
  related: [
    { slug: "indiabulls-securities", name: "Indiabulls Securities", category: "Financial services" },
    { slug: "pepperfry", name: "Pepperfry", category: "Furniture & home decor" },
  ],
};
